[workspace]
members = [
    "quanta-artifact",
    "quanta-crypto",
    "quanta-walker",
    "quanta-swap",
]

[workspace.dependencies]
async-std = "1.12.0"
async-trait = "0.1.68"
base64ct = { version = "1.6.0", features = ["alloc"] }
bs58 = "0.5.0"
bincode = "1.3.3"
blake3 = "1.4.0"
digest = "0.10.7"
fnv = "1.0.7"
futures = "0.3.28"
hex = "0.4.3"
libp2p = { version = "0.51.3", features = ["request-response", "async-std", "gossipsub", "mdns", "noise", "macros", "tcp", "yamux"] }
log = "0.4.19"
pretty_env_logger = "0.5.0"
prost = "0.11.9"
prost-build = "0.11.9"
quanta-crypto = { path = "quanta-crypto" }
rand = "0.8.5"
sha3 = "0.10.8"
sha2 = "0.10.7"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
libflate = "1.4.0"
