[package]
name = "quanta-database"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = { workspace = true }
log = { workspace = true }
quanta-artifact = { workspace = true }
quanta-swap = { workspace = true }
sled = { workspace = true }
thiserror = { workspace = true }
