[package]
name = "quanta-artifact"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
quanta-crypto = { workspace = true }
